apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotbot-deployment
  labels:
    app: cotbot
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cotbot
  template:
    metadata:
      labels:
        app: cotbot
    spec:
      containers:
      - name: cotbot
        image: cotbot:latest
        args: ["udpWithDetails"]
        imagePullPolicy: IfNotPresent
        env:
        - name: remoteHost
          value: "192.168.29.145"
        - name: MY_BOT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
