apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotbot-deployment
  labels:
    app: cotbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cotbot
  template:
    metadata:
      labels:
        app: cotbot
    spec:
      containers:
      - name: cotbot
        image: cotbot:1.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: remoteHost
          value: "192.168.29.145"