apiVersion: v1
kind: Pod
metadata:
  name: cotbot
  labels:
    app: cotbot
spec:
  containers:
  - name: cotbot
    image: cotbot:1.0.1
    imagePullPolicy: IfNotPresent
    env:
    - name: remoteHost
      value: "192.168.29.145"
  restartPolicy: Always