apiVersion: v1
kind: Pod
metadata:
  name: cotbot
  labels:
    app: cotbot
spec:
  containers:
  - name: cotbot
    image: cotbot:latest
    args: ["udpWithDetails"]
    imagePullPolicy: IfNotPresent
    env:
    - name: remoteHost
      value: "192.168.29.145"
    - name: MY_BOT_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name   
  restartPolicy: Always